# Ice Default locator
Ice1.Default.Locator=\
  BrIceGrid/Locator:\
  tcp -h ice1-master.brapp.com -p 4061:\
  tcp -h ice1-replica.brapp.com -p 4061
Ice2.Default.Locator=\
  DacIceGrid/Locator:\
  tcp -h ice2-master.brapp.com -p 4061:\
  tcp -h ice2-replica.brapp.com -p 4061
# Ice1 prop

# If not defined, the default value is 60.
# Ice1.ACM.Timeout=0

# \uFFFD\u07F3\u0333\u0633\uFFFD\u02BC\uFFFD\uFFFD\u0421
Ice1.ThreadPool.Client.Size=20
# \uFFFD\u07F3\u0333\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD
Ice1.ThreadPool.Client.SizeMax=100
# ICE\uFFFD\uFFFD\uFFFD\uFFFD\u037B\uFFFD\uFFFD\uFFFD\uFFFD\u07F3\uFFFD\u057B\uFFFD\uFFFD\u0421\uFFFD\uFFFD\uFFFD\uFFFD
Ice1.ThreadPool.Client.StackSize=4096
# \uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u04F3\uFFFD\u02B1\u02B1\uFFFD\uFFFD
Ice1.Override.ConnectTimeout=2000
# \uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u00F3\uFFFD\u02B1\u02B1\uFFFD\uFFFD
Ice1.Default.InvocationTimeout=20000
# If this property is not defined, the default behavior is to retry once immediately after the first failure
Ice1.RetryIntervals=0 1000 5000
# \uFFFD\uFFFD\uFFFD\uFFFD
Ice1.ACM.Heartbeat=2
# \uFFFD\uFFFD\uFFFD\u0631\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD
Ice1.ACM.Close=0
# \uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u03E2\uFFFD\uFFFD\u0421, \u012C\uFFFD\uFFFD\u05B51024KB
Ice1.MessageSizeMax=65536
# \uFFFD\uCCBD\uFFFD\uFFFD\uFFFD\u00B7\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u03E2
# Ice1.BackgroundLocatorCacheUpdates=1
# Ice1.Default.LocatorCacheTimeout=300
# \uFFFD\uFFFD\uFFFD\uFFFD\u02B9\uFFFD\uFFFD
# Ice1.Trace.Network=1
# Ice2 prop
# Ice2.ACM.Timeout=0
Ice2.ThreadPool.Client.Size=20
Ice2.ThreadPool.Client.SizeMax=100
Ice2.ThreadPool.Client.StackSize=4096
Ice2.Override.ConnectTimeout=2000
Ice2.Default.InvocationTimeout=20000
Ice2.RetryIntervals=0 1000 5000
Ice2.ACM.Heartbeat=2
Ice2.ACM.Close=0
Ice2.MessageSizeMax=65536
# Ice2.BackgroundLocatorCacheUpdates=1
# Ice2.Default.LocatorCacheTimeout=300
# Ice2.Trace.Network=1
# Ice \uFFFD\u0536\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD
# \u0368\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u02B1\uFFFD\uFFFD
Ice1.IdleTimeOutSeconds=86400
Ice2.IdleTimeOutSeconds=86400