spring:
  web.interceptors.enabled: true
  application:
    name: marketing-xc-general
  profiles.active: pre
  aop:
   proxy-target-class: true
   auto: true
  threadpool:
    queueCapacity: 10000
    # 线程池所使用的缓冲队列
    corePoolSize: 8
    # 线程池维护线程的最少数量
    maxPoolSize: 100
    # 线程池维护线程的最大数量
    keepAliveSeconds: 30000
    # 线程池维护线程所允许的空闲时间
    threadNamePrefix: ThreadPool-Common
    # 线程池所生产的线程名前缀
  rabbitmq:
    zw:
      addresses: delivery-rabbitmq-cluster-01.brapp.com:5672
      username: strategy_distribute
      password: strategy_distribute
      publisher-confirms: true
      publisher-returns: true
      virtual-host: marketing-flow
    yz:
      addresses: delivery-rabbitmq-cluster-01.brapp.com:5672
      username: strategy_distribute
      password: strategy_distribute
      publisher-confirms: true
      publisher-returns: true
      virtual-host: marketing-flow
    listener:
      retry:
        enabled: true
        max-attempts: 5
        initial-interval: 3000
      acknowledge-mode: manual
      default-requeue-rejected: false
      auto-startup: true
server:
  port: 16707

#生成结果文件目录
result.file.path: /opt/data/inloan/warning
#exporter监控
endpoints:
  prometheus:
    enabled: true
    path: /prometheus
    sensitive: false