spring:
  web.interceptors.enabled: true
  application:
    name: marketing-data-monkey
  profiles.active: prod
  aop:
   proxy-target-class: true
   auto: true
  threadpool:
    queueCapacity: 10000
    # 线程池所使用的缓冲队列
    corePoolSize: 8
    # 线程池维护线程的最少数量
    maxPoolSize: 100
    # 线程池维护线程的最大数量
    keepAliveSeconds: 30000
    # 线程池维护线程所允许的空闲时间
    threadNamePrefix: ThreadPool-Common
    # 线程池所生产的线程名前缀
server:
  port: 16707

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#exporter监控
endpoints:
  prometheus:
    enabled: true
    path: /prometheus
    sensitive: false
