sharding:
  jdbc:
    datasource:
      names: ds0
      ds0:
        url: jdbc:mysql://tidb-pre.brapp.com:4000/marketing?useUnicode=true&characterEncoding=UTF-8&connectTimeout=3000&socketTimeout=300000&autoReconnect=false&failOverReadOnly=false&useConfigs=maxPerformance
        username: u_pd_marketing
        password: M6teKbFVl1odfOCkC1JA
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 300
        initialSize: 5
        maxWait: 30000
        minIdle: 5
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  config:
    sharding:
      props:
        sql.show: true
spring:
  rabbitmq:
    zw:
      addresses: delivery-rabbitmq-cluster-01.brapp.com:5672
      username: strategy_distribute
      password: strategy_distribute
      publisher-confirms: true
      publisher-returns: true
      virtual-host: marketing-flow
    yz:
      addresses: delivery-rabbitmq-cluster-01.brapp.com:5672
      username: strategy_distribute
      password: strategy_distribute
      publisher-confirms: true
      publisher-returns: true
      virtual-host: marketing-flow-yz
    listener:
      retry:
        enabled: true
        max-attempts: 5
        initial-interval: 3000
      acknowledge-mode: manual
      default-requeue-rejected: false
      auto-startup: true
  web:
    interceptors.enabled: true
  sql.source: prod
cluster:
  flag: ${CONF_CLUSTER}
otherConfig:
  alarm:
    secretKey: a9c57e4138807a9e18b439cd9dab275b
    appName: marketing
    outsideSecretKey: 71e63ead0af0a07ae4191eb14b75a541
    outsideAppName: marketing-out
  encodeMapping:
    appName: loan-warning
    appSecretKey: f15a1421ac95a284683688af14688b72
  userCenter:
    appName: loan-strategy
    appSecretKey: 404be42e9ad8ce59af79f17eb51594cf
  mom:
    appSecretKey: d42726322ba9bda57b74043be21aa2c4
    appName: marketing_query_producer
    destinationName: marketing_query_log
  proxy:
    proxy_host: squid-proxy-pre.brapp.com
    proxy_port: 3128
    proxy_username: spmarketing
    proxy_password: ek1EIgo9
    proxy_host_zw: 10.100.123.221
  #mom上传日志
  uploadMom:
    producerKey: marketing_api_upload_producer
    appSecretKey: 3a78162475b96285ea70a9edb6438ba4
    destinationName: marketing_api_upload_log
    logIceTimeout: 2000
api:
  intelligentCustomerService:
    baseUrl: http://k8s.brapp.com/compass-api/api/helios-app-api
    pushUserUrl: ${api.intelligentCustomerService.baseUrl}/third/process/data  #推送智能客服接口
  robotAiApiService:
    baseUrl: http://k8s.brapp.com/compass-api/api/robotai-api-service
    robotOutboundUrl: ${api.robotAiApiService.baseUrl}/api/robotOutbound  #转化推送智能客服
  zhongAn:
    baseUrl: https://finance-gateway-test.diandian.com.cn
    api: ${api.zhongAn.baseUrl}/fcpGateway
    isProxy: true
    rsapKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCVuaxc7ZznPdvsH0nhd2eQ/uhu/LewJqUVMvdYUKwXPxzGBUz8cVKyltwpMJ03uMPx+RStWnkWcmCSeQdqiw27FtaPELOxxQQc06OGBXfp5R86MKp2+bkdPRSkpUKK2X8vCyiopQojBXbaVzRUwjPPsQAsDinCGkSUirWETxfCxwIDAQAB
    xdCode: 07brdyy01
    bxCode: 3360001
  customerService:
    apiCode: 4000296
  dass:
    aesKey: ovksl39fcl13m9dF
rocketmq:
  # 多个NameServer，host:port;host:port，RocketMQProperties
  name-server: 10.100.123.171:9876;10.100.123.172:9876;10.100.123.173:9876
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    group: Marketing_PreUser_Receive
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 发送消息超时时间，默认3000
    sendMessageTimeout: 5000
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false
    # access-key
    #accessKey: xxx
    # secret-key
    #secretKey: xxx
    # 是否启用消息跟踪，默认false
    enableMsgTrace: false
    # 消息跟踪主题的名称值。如果不进行配置，可以使用默认的跟踪主题名称
    customizedTraceTopic: RMQ_SYS_TRACE_TOPIC
  consumer:
    # 配置指定group是否启动监听器 group1.topic1 = false
    # 配置指定group是否启动监听器 group1.topic1 = false
    listeners:
      # key：group名称
      rocketmq_source_code_group:
        # value：{key: topic名称: value: true/false}
        rocketmq_source_code: true
    # 指定消费组
    group: Marketing_PreUser_Receive
    # 指定topic，启动时就会注册
    #topic: springboot_consumer_xxx
    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
    pull-batch-size: 10
    # 其他配置参考属性类