sharding:
  jdbc:
    datasource:
      names: ds0
      ds0:
        url: jdbc:mysql://192.168.23.110:3306/marketing?useUnicode=true&characterEncoding=UTF-8
        username: u_pd_marketing
        password: M6teKbFVl1odfOCkC1JA
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 300
        initialSize: 5
        maxWait: 60000
        minIdle: 5
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  config:
    sharding:
      props:
        sql.show: true
eureka:
  client:
    service-url.defaultZone: http://192.168.23.121:18000/eureka/

spring:
  rabbitmq:
    addresses: 192.168.23.73:5672
    username: strategy_distribute
    password: strategy_distribute
    publisher-confirms: true
    publisher-returns: true
    virtual-host: marketing-flow

api:
  intelligentCustomerService:
    baseUrl: https://helios-pre.100credit.com/zuul/api/helios-app-api
    pushUserUrl: ${api.intelligentCustomerService.baseUrl}/third/process/data  #推送智能客服接口