#��ĿӢ����
appName=loan-strategy-api
#��Դ�����Ŀ���������
redis.max.idle=10
#��Դ�����ٵĿ���������
redis.min.idle=10
#��Դ������������
redis.max.total=50
#�������þ�ʱ�����������ȴ�ʱ��(����)
redis.max.wait.time=6000
#�����ӳؽ�������ʱ���Ƿ�Ҫ����������Ч�Լ�⣨ping������Ч���ӻᱻ�޳�
redis.test.onBorrow=true
#�����ӳع黹����ʱ���Ƿ�Ҫ����������Ч�Լ�⣨ping������Ч���ӻᱻ�޳�
redis.test.onReturn=false
#�Ƿ���������Դ���
redis.test.whileIdle=true

redis.conn.timeout=1000
redis.read.timeout=1000
redis.max.redirect.count=10
redis.clusterIp=\
  redis-cluster1-01.brapp.com:7360,\
  redis-cluster1-02.brapp.com:7360,\
  redis-cluster1-03.brapp.com:7360