# Ice Default locator
Ice1.Default.Locator=\
  BrIceGrid/Locator:\
  tcp -h ice1-master.brapp.com -p 4061:\
  tcp -h ice1-replica.brapp.com -p 4061
Ice2.Default.Locator=\
  DacIceGrid/Locator:\
  tcp -h ice2-master.brapp.com -p 4061:\
  tcp -h ice2-replica.brapp.com -p 4061
# Ice1 prop
# \u7EBF\u7A0B\u6C60\u521D\u59CB\u5927\u5C0F
Ice1.ThreadPool.Client.Size=20
# \u7EBF\u7A0B\u6C60\u6700\u5927\u6570
Ice1.ThreadPool.Client.SizeMax=100
# ICE\u670D\u52A1\u5BA2\u6237\u7AEF\u7EBF\u7A0B\u6808\u5927\u5C0F\u8BBE\u7F6E
Ice1.ThreadPool.Client.StackSize=4096
# \u5EFA\u7ACB\u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
Ice1.Override.ConnectTimeout=2000
# \u670D\u52A1\u8C03\u7528\u8D85\u65F6\u65F6\u95F4
Ice1.Default.InvocationTimeout=10000
# If this property is not defined, the default behavior is to retry once immediately after the first failure
Ice1.RetryIntervals=0 1000 5000
# \u5FC3\u8DF3
Ice1.ACM.Heartbeat=2
# \u4E0D\u5173\u95ED\u8FDE\u63A5
Ice1.ACM.Close=0
# \u6700\u5927\u6D88\u606F\u5927\u5C0F, \u9ED8\u8BA4\u503C1024KB
Ice1.MessageSizeMax=65536
# Ice2 prop
# Ice2.ACM.Timeout=0
Ice2.ThreadPool.Client.Size=20
Ice2.ThreadPool.Client.SizeMax=100
Ice2.ThreadPool.Client.StackSize=4096
Ice2.Override.ConnectTimeout=2000
Ice2.Default.InvocationTimeout=10000
Ice2.RetryIntervals=0 1000 5000
Ice2.ACM.Heartbeat=2
Ice2.ACM.Close=0
Ice2.MessageSizeMax=65536
# Ice \u81EA\u5B9A\u4E49\u914D\u7F6E
# \u901A\u4FE1\u5668\u7A7A\u95F2\u65F6\u95F4
Ice1.IdleTimeOutSeconds=86400
Ice2.IdleTimeOutSeconds=86400