#\uFFFD\uFFFD\u013F\u04E2\uFFFD\uFFFD\uFFFD\uFFFD
appName=marketing-inner-api
#\uFFFD\uFFFD\u0534\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u013F\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD
redis1.max.idle=10
#\uFFFD\uFFFD\u0534\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0675\u013F\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD
redis1.min.idle=10
#\uFFFD\uFFFD\u0534\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD
redis1.max.total=50
#\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u00FE\uFFFD\u02B1\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0234\uFFFD\u02B1\uFFFD\uFFFD(\uFFFD\uFFFD\uFFFD\uFFFD)
redis1.max.wait.time=6000
#\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u04F3\u063D\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u02B1\uFFFD\uFFFD\uFFFD\u01F7\uFFFD\u04AA\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0427\uFFFD\u053C\uFFFD\u28E8ping\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0427\uFFFD\uFFFD\uFFFD\u04FB\u1C7B\uFFFD\u07B3\uFFFD
redis1.test.onBorrow=true
#\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u04F3\u0639\u9EF9\uFFFD\uFFFD\uFFFD\uFFFD\u02B1\uFFFD\uFFFD\uFFFD\u01F7\uFFFD\u04AA\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0427\uFFFD\u053C\uFFFD\u28E8ping\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0427\uFFFD\uFFFD\uFFFD\u04FB\u1C7B\uFFFD\u07B3\uFFFD
redis1.test.onReturn=false
#\uFFFD\u01F7\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u0534\uFFFD\uFFFD\uFFFD
redis1.test.whileIdle=true

redis1.conn.timeout=1000
redis1.read.timeout=1000
redis1.max.redirect.count=10
#redis1\uFFFD\uFFFD\u023A \uFFFD\uFFFD\uFFFD\uFFFD---
#redis1.clusterIp=\
#  redis-strategy-01.brapp.com:7340,\
#  redis-strategy-02.brapp.com:7340,\
#  redis-strategy-03.brapp.com:7340,\
#  redis-strategy-04.brapp.com:7340,\
#  redis-strategy-05.brapp.com:7340,\
#  redis-strategy-06.brapp.com:7340
#redis1\uFFFD\uFFFD\u023A \u0524\uFFFD\uFFFD---
redis1.clusterIp=\
  redis-strategy-01.brapp.com:7360,\
  redis-strategy-02.brapp.com:7360,\
  redis-strategy-03.brapp.com:7360
redis2.max.idle=50
redis2.min.idle=10
redis2.max.total=50
redis2.max.wait.time=6000
redis2.test.onBorrow=true
redis2.test.onReturn=false
redis2.test.whileIdle=true
redis2.conn.timeout=1000
redis2.read.timeout=1000
redis2.max.redirect.count=10
#redis2\uFFFD\uFFFD\u023A \uFFFD\uFFFD\uFFFD\uFFFD---
#redis2.clusterIp=\
#  marketing-redis-cluster-01.brapp.com:7310,\
#  marketing-redis-cluster-01.brapp.com:7311,\
#  marketing-redis-cluster-01.brapp.com:7312,\
#  marketing-redis-cluster-02.brapp.com:7310,\
#  marketing-redis-cluster-02.brapp.com:7311,\
#  marketing-redis-cluster-02.brapp.com:7312
#redis1\uFFFD\uFFFD\u023A \u0524\uFFFD\uFFFD---
redis2.clusterIp=\
  redis-strategy-01.brapp.com:7360,\
  redis-strategy-02.brapp.com:7360,\
  redis-strategy-03.brapp.com:7360
redis4.max.idle=50
redis4.min.idle=10
redis4.max.total=50
redis4.max.wait.time=6000
redis4.test.onBorrow=true
redis4.test.onReturn=false
redis4.test.whileIdle=true
redis4.conn.timeout=1000
redis4.read.timeout=1000
redis4.max.redirect.count=10
#redis4\u96C6\u7FA4
redis4.clusterIp=\
  10.100.123.157:7360,\
  10.100.123.158:7360,\
  10.100.123.159:7360