datasource:
  database:
    names: shardingmarketing,marketingTikiv,marketingTiFlash
    defaultSource: shardingmarketing
    shardingmarketing:
      url: jdbc:mysql://tidb-pre.brapp.com:4000/marketing?useUnicode=true&characterEncoding=UTF-8
      username: u_pd_marketing
      password: M6teKbFVl1odfOCkC1JA
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      isSharding: true
      filters: stat
      maxActive: 300
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    marketingTikiv:
      name: marketing
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://tidb-pre.brapp.com:4000/marketing?useUnicode=true&characterEncoding=UTF-8
      username: u_pd_marketing
      password: M6teKbFVl1odfOCkC1JA
      initialSize: 5 # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      minIdle: 5 # 最小连接池数量
      maxActive: 200 # 最大连接池数量
      maxWait: 60000 # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置
      timeBetweenEvictionRunsMillis: 60000 # 关闭空闲连接的检测时间间隔.Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
      minEvictableIdleTimeMillis: 300000 # 连接的最小生存时间.连接保持空闲而不被驱逐的最小时间
      validationQuery: SELECT 1 FROM DUAL # 验证数据库服务可用性的sql.用来检测连接是否有效的sql 因数据库方言而差, 例如 oracle 应该写成 SELECT 1 FROM DUAL
      testWhileIdle: true # 申请连接时检测空闲时间，根据空闲时间再检测连接是否有效.建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRun
      testOnBorrow: false # 申请连接时直接检测连接是否有效.申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false # 归还连接时检测连接是否有效.归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      poolPreparedStatements: true # 开启PSCache
      maxPoolPreparedStatementPerConnectionSize: 20 #设置PSCache值
      connectionErrorRetryAttempts: 5 # 连接出错后再尝试连接三次
      breakAfterAcquireFailure: true # 数据库服务宕机自动重连机制
      timeBetweenConnectErrorMillis: 300000 # 连接出错后重试时间间隔
    #      removeAbandoned: true # 是否自动回收超时连接
    #      removeAbandonedTimeout: 1800 # 超时时间(以秒数为单位)
    #      filters: stat,wall,log4j2
    #      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    marketingTiFlash:
      name: marketing
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://tidb-pre.brapp.com:4020/marketing?useUnicode=true&characterEncoding=UTF-8
      username: u_pd_marketing
      password: M6teKbFVl1odfOCkC1JA
      initialSize: 4 # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      minIdle: 4 # 最小连接池数量
      maxActive: 4 # 最大连接池数量
      maxWait: 60000 # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置
      timeBetweenEvictionRunsMillis: 60000 # 关闭空闲连接的检测时间间隔.Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
      minEvictableIdleTimeMillis: 300000 # 连接的最小生存时间.连接保持空闲而不被驱逐的最小时间
      validationQuery: SELECT 1 FROM DUAL # 验证数据库服务可用性的sql.用来检测连接是否有效的sql 因数据库方言而差, 例如 oracle 应该写成 SELECT 1 FROM DUAL
      testWhileIdle: true # 申请连接时检测空闲时间，根据空闲时间再检测连接是否有效.建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRun
      testOnBorrow: false # 申请连接时直接检测连接是否有效.申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false # 归还连接时检测连接是否有效.归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      poolPreparedStatements: true # 开启PSCache
      maxPoolPreparedStatementPerConnectionSize: 20 #设置PSCache值
      connectionErrorRetryAttempts: 5 # 连接出错后再尝试连接三次
      breakAfterAcquireFailure: true # 数据库服务宕机自动重连机制
      timeBetweenConnectErrorMillis: 300000 # 连接出错后重试时间间隔
#      removeAbandoned: true # 是否自动回收超时连接
#      removeAbandonedTimeout: 1800 # 超时时间(以秒数为单位)
#      filters: stat,wall,log4j2
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

logging:
    level:
        com.br.off.mapper: debug
    file: ./logs/core.log
    root: INFO
otherConfig:
  alarm:
        secretKey: a9c57e4138807a9e18b439cd9dab275b
        appName: marketing
        outsideSecretKey: 71e63ead0af0a07ae4191eb14b75a541
        outsideAppName: marketing-out
  userCenter:
        appName: loan-strategy
        appSecretKey: 404be42e9ad8ce59af79f17eb51594cf
  warning:
        pageSize: 5000
        apiUrl: http://compass-api.100credit.com/api/loan-warning-api/loanStrategy/v2/query
        path: /opt/data/inloan/download/marketing/
        sftpHost: 10.100.123.65
        sftpPort: 9999
        sftpUser: BRmarketing_pre
        sftpPwd: 72aXd79ITcMeuyPAlDYy@_2021.06.07
  encodeMapping:
        appName: loan-warning
        appSecretKey: f15a1421ac95a284683688af14688b72
  proxy:
    proxy_host: squid-proxy2.brapp.com
    proxy_port: 3128
    proxy_username: bairong
    proxy_password: Proxy_br
    proxy_host_zw: 192.168.22.169
  mom:
    appSecretKey: d42726322ba9bda57b74043be21aa2c4
    appName: marketing_query_producer
    destinationName: marketing_query_log
cluster:
  flag: ${CONF_CLUSTER}
api:
  intelligentCustomerService:
    baseUrl: http://k8s.brapp.com/compass-api/api/helios-app-api
    pushUserUrl: ${api.intelligentCustomerService.baseUrl}/third/process/data  #推送智能客服接口
  robotAiApiService:
    baseUrl: http://k8s.brapp.com/compass-api/api/robotai-api-service
    robotOutboundUrl: ${api.robotAiApiService.baseUrl}/api/robotOutbound  #转化推送智能客服
  yiQianBao:
    baseUrl: https://teststable4-www-pmgw.stg.1qianbao.com
    pushMarketingData: ${api.yiQianBao.baseUrl}/pmgw/18/GI180098/PM180022/commonRequest #营销数据推送壹钱包
    rsaPubKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnYI7ITjERAtNMOUsR2i1Tt0Jt7ku9+sRKpv17UIXleE3eDJQO4bK2al1hySHoKpKqvXN/TBQh+tlZNcDqcaEqc5B5V3+ohdvKciae+d6vohc2SkLxcmxc9jseS9NsZ6UWrCrSad/BiNiOAevioAL0pUK+HL3yRrLyr/S8nbc/0qKoHsF+rhqbw72QcUL63Kl4gq/8/hAEHU6HGvT5cgDuymtdRyT2jMkOTkyu32vX8SUapa2YZi1FmOPsvbeNKnVteBCVpDLRCcYR11yuFO8olSEELOFc4uHwxwOXNWg/J0ps60mRmntBsaFbd/pMkYbPJ/OVBO0PHvSQG/5Gy4qewIDAQAB"
    brPrivateKey: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCnyVDp07vw7+/wkrO6M2zEmlt9vKnFlTkZEJ0HQC7DsmyYiNlLFPJEbFqW4Urssh0Gj+neEgsUyrSVuFhhsZACTfckPEdtOr8SpcbkkgCOZ2fP/wjy7uPmeThdlebWZSIHQN0whHhv5euQf0ze3IIZnAjPvCERf8tI8Wu3YGp7VPu/XEntsaesc6wuteCB8UnWGVJvayKbmT+DVqcroIbV4j7JSbbj/8VDQ0+RjBxkf/Z8ReNfGhZ6UGIIFKykvLKfUTwgEBttlDfdKfMpUlg0gRbksbuSV6H6cETK/YqRgcROe1YLm/fXLh+nBzbwvq9jjUzDQPz99APUACD2bsuHAgMBAAECggEAcfQaThSNij+K+BrKkeWnM4eaJ7VgoF6OnuVXoLsIh8TAWIBpA8NAHxRwGhT86/C0IebP8RDUEdTx/NVswTz1D3ugJC4EXL0PVDze7hHy6sR0DyGpFEUG51rg2z6ZvnaFO+Pj1bXCjkzbRhIPRTUB7x64JU4iL15Z1DqS68JBz2x4yofJgKcF8A3cQq9BV5iNwURmVdrTM8ruwvQ8/fnJpHVbznHZlMbyLlvp1FNmQWErhryoYPiAqajxx0HoppRW41q+ZIt5z/PxKOA1L64mOT3W0WpTwHJGpTkQDIVLFh8vkSNUJIi8y/Qg9a5LJBTVSG40ndPlsZkWm5gJhfcWkQKBgQDUj1KuPAurQkDOza3XkXLU9RgZv21KHAb9oTzmb+gkoZWx/f/dUfmocS5YE0llfq7f81VcPD7bFq3s7j0TXeaH/UUc4yLmrfkdzUqPg01RQUWw3bknjZ6S3XAP1rNWVWWLFWNJ9YEIJIJXecUmFKB8Fypqr33bClvl0CGKzitjvQKBgQDKE4qLpQm8pbdvduPSvmYbvjIZoLhrN0kVWBfMM1jpHzg+36mOEohhAMuQmOIQB74Ubi609HK0vslxxoEnarhpR8ArQFIbzToULeM+DqexLO5ODDW1yXKVziBN8+cM1xyveOtLBS3fyQcQk/YhLjQp0AeodVP4ViLdmw/HUjv+kwKBgQC5Q4Y76If/J8rWtPw9ND+TD2CHKIq4Gj+Zlow/CPCb5N5Ved4l58ojHyrWh1DkjosbFLqknrnmORk0td0z4RcKFhzD9dC4oI/Ngt3mwfmExdBZPJehutSoiyqeE3LR37KWi/izQLDLCQ818SN9cmMCZSqKPBUE8j1wy3xAwDufPQKBgHHHwPnSCoJ6+Kc9VRgjdtDmLcV6VnygG3l2KagjvUs99eiI/SpuyvV7giM/wgHuqhtM0uW2wiN9TWXPtIciMwWsjcqMo+7dhnc4Qzx8+fTr7J5rh459CBTLhCsASzdSo+c1eZ67ItJfmae++BZEssBcTwOOVKJ+tZD7r022wusbAoGBAJI8tUL0A/2JAcwhl6hrB1dFgB8EdGrEceCaFwuYzOt2mcfcViU4HOOilOIRSuZDONKLhfoVmS5hS+WOPWZMaJpUIOz/Fi/XnWkRxGOcr1eOuNLPQMRArCkieBX6dmlX2Tf3lRN8cX4x4aGOgOm2sUd3koa5K/9uMXkeSKJPrJNy"
    salt: e9d46339e4edc515
    isProxy: 1
  dass:
    baseUrl: http://testdaas.huiyunai.com
    postHermesUserData: ${api.dass.baseUrl}/csos-daas/call/postHermesUserData
    postBlackList: ${api.dass.baseUrl}/csos-daas/call/postBlackList # 黑名单数据推送
    postRealTimeUserData: ${api.dass.baseUrl}/csos-daas/call/postRealTimeUserData # 实时单条用户名单数据推送
    postTransferData: ${api.dass.baseUrl}/csos-daas/call/postDealData # 转化数据推送
    aesKey: ovksl39fcl13m9dF
    SecretKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJ4W9Hw1Kb6g0RevKSeKqriBCup3x8V2G2J63imkypbtPV+RJjq4eCqcd7s2FI/9eTSMw17675Ey9MkKndIckvpxT1iCtUnuRbg1ICtZ127t65GhOPchBzWHoC+rG56Rw4NhpsvpIGC1y4EUx26TyNop7HRekKwosAnnl6QDWBEdAgMBAAECgYAkX7W7CmRjdw8E+wlmDrK/JvnC/vJZDZa5bvnE7SSr20Qew//ezOjhLQUjbwsGIlUL8UNWjDgo2WeXBjlPycFLP8YN/+gUPR/bfftUY4cTnWzAAKKyUJBeyt3SqaeYcUhW3aUCUlaVAb8ZdyIu4WlHYHhlkSoXrDRvnqlJmyj8wQJBAMzApuvsJDZIX6qvMGR6YTvqPIsl47+qIlk7iTUfwbjGz5zlFtu4IRd+ZVdHlncg5arrl+lOw33rkHhxtnV8jO0CQQDFqGsIPk4Nnwsx9XtCCrYePvgydzEAT1nr4gBUkXbvavMyJKsQWI5AXUAInNuqxRvNfjh3GMaWstIsMQJyDj7xAkEAglL1bCEIA40ZZ1jO4oWKskorcx4Q0oQGDOn6MVgfQ+83YlPmsr+GQJ/w/RbRzM2hoaMHNDcv80wmzqMCUdGPGQJAKIHuhX73UhVRHwj3HL7DOgmfpgAFW9HnVM85UBuLq19YveMD59KuPISf1eQHpMTGgOOoQMgkEshNCF9259cBkQJBAKIlpXnTHvv2M96B7w7T1RYVvjke4LLpCbAVd8fBciOdFLmMh0+FThxGWijgfow1XYaPrU0DlfLpkfLrgk3LWUQ=
    isProxy: 1
  twoSeven:
    baseUrl: http://8.129.19.178:8888
    zhuangku: ${api.twoSeven.baseUrl}/zhuangku
    isProxy: 1
  haier:
    apiCode: "2a43ad9e9b6a247ef9613761dcb191d7"
    apiKey: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCTMUmWLeOWOvpr7FzXNOXFShZfh5MM8tz7K57bWFzj4vNRwenafTgX+nOacO2QDH4yvNFS1bwzw0sc0BvWscrbCFf80g81lmBBnxVZJkHID/RKj35gw/SjPg2hSReQwTGL3m7lYhYruMFZDIEZ0O2xKNroiPIj+f/FbJAkJ6ezaQIDAQAB"
    baseUlr: http://${api.haier.host:60.209.94.196:8088}/
    custData:
      receive:
        url: ${api.haier.baseUlr}app/marketControl/custData/receive
        info:
          url: ${api.haier.custData.receive.url}/info
  marketing:
    baseUrl: http://marketing-api
    transferUrl: ${api.marketing.baseUrl}/marketingTransferData/receiveTransferDataSync
    uploadUrl: ${api.marketing.baseUrl}/marketingUserPre/receiveMarketingPreUser
  halo:
    openUrl: https://fat-hello-openapi.hellobike.com/openapi
    appKey: hellobikefinance-bwYuIVvO
    secret: b3392af427b6449e94269433bdf5fb58
    method: hello.finance.loan.marketing.callback
    isProxy: true
  xiecheng:
    openUrl: https://cgcallback-fat.ctripqa.com/nemoweb/ad/common/outAdMonitor.do
    appId: bairong001
    appIdVt: test002
    keyVt: 6b219b9e71fdb2d2
    ivVt: 5e7b6c07d3edbc01
    signKeyVt: b8845b4cb1f16471
    key: f3df6f62f0527bf0
    iv: 3b2dac323465b024
    singKey: 95cc01ec07387a44
    source: BaiRong_C01
    channel: commonOutAdMonitor
    isProxy: true
  zhongAn:
    baseUrl: https://finance-gateway-test.diandian.com.cn
    api: ${api.zhongAn.baseUrl}/fcpGateway
    isProxy: true
    rsapKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCVuaxc7ZznPdvsH0nhd2eQ/uhu/LewJqUVMvdYUKwXPxzGBUz8cVKyltwpMJ03uMPx+RStWnkWcmCSeQdqiw27FtaPELOxxQQc06OGBXfp5R86MKp2+bkdPRSkpUKK2X8vCyiopQojBXbaVzRUwjPPsQAsDinCGkSUirWETxfCxwIDAQAB
    xdCode: 07brdyy01
    bxCode: 3360001
  didi:
    baseUrl: https://admarketing-manhattan.xiaojukeji.com
    smsUrl: ${api.didi.baseUrl}/crow/collision/bairong
    reachUrl: ${api.didi.baseUrl}/crow/user/success/bairong
    jmassSUrl: ${api.didi.baseUrl}/model/sample/mediaName
    failedUrl: ${api.didi.baseUrl}/crow/faileduser/mediaName
    token: DK&SgWl!fZ%WVSXe
    scas: "0001"
    channelId: 3140738836439875
    channelIdMap: "{bairong:'3140738836439875',bairongA:'3140738898634899'}"
    isProxy: true
  qifu:
    baseUri: https://stg1-gws-bps-web.daikuan.360.cn
    saveReachDeleteRecordUrl: ${api.qifu.baseUri}/api/gws/bps/gateway/agent/operation/agentOperationSaveReachDeleteRecord
    qifuPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwQAaMvE6+7Wy+rf6jfW8OEKhGSmmg6LaiSLaTui3lBA4V4eqfQEpLfL8dGYYcakiH6CUAMPZ0jqNEN/En3Mtfclhr8903m/xG3IOUxhbqiVZBZmQ8esG6nP8MHsFWK2hMHN20xh0qKN6hg0BHQIIkbbnZjN9FGD/hz1t4NJvwIHxqJC+I3pRkCrC+SPWH5djzQdhYczgpyGwNqrGpg5dPibZJ+/qw15Va0vDBMp8cGad+Njcw5n7QcxBvSpViTYl704+wyohX36bF1CkrtfV6z1JnDqR+9KtEaRpfnUC/eh7gvltDbl/vTfeZLuShLs+/csgVshVIXEpL8g9uC0XOQIDAQAB"
    brPrivateKey: "MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDdAO5CXKe5ugLICKdPeAXE7/4V484BPYdZVMoexCoWN7vwFV1dW8AyjsOYvvMOYSd/MOCqE0sK4CN/Tf857nalMqA5oU+MIEUkbb+KyXFXpNFi/LLi8FGGHQgTQFAS+Tikz1sHtYg3W8G7wQJsTDKXGQ7dEH9pJv3RbGZzQnTlzj/1brJ8uDGXYmKVPr2MbuOmtzCzzd9O0cPO1fEVwpnJbAUfQxZleMUL21OpkmTjqIBQfANf/24DjbJelZjRUA7YIR42XpxGXWeOlXR1D3jzIN0lguacwy+en3JvhbC62E6f04rzqs3TThlKxH4cjFZjOPvoGml2Z43S1k46lPjtAgMBAAECggEBANTyjKFM/iArZ3qvO+eK0qRMSxt0gY8YZk5hMNAsXBFEasaPD4NhYPRWM4n+k9yLKK+ZvSCjrm8wQYPs97wuVgwfl9tv32I5xeWwChwEtj2pBkjHDOc2gJclah6CnaVqlnXXhvMKq9ILi8UJ2PfZA/YrovLHbr03YOJl/OGaa2DxbIyDQsz8LH/4o7QLaRkAkwZw3egd/jepSB9hZwZ8NghkpqbSnRokjH+Rfx9b8uQ/MIqIfDXD8gMCALV+JFjG60mP/yGYS9xb1pHiW07M3QphYo8IV+X1YCnJ1nt7FrAQaPUIe+/zJhFsBM7EN6hX4RdqTacnpKZ0IfEOn/jU9YECgYEA9DLxbNPaAm5HnBA0tD7euFokyP9td8+EVhjeMPCZqPlVnWDm3c9bdrAWQbtwyMA0gvkcELtgFnPf0ICuV2FCKaTPtPa6C73ZR5ElBWkJ/pSbyYw8YGvN98Nh8xbEVqippN5Ypp8vQrZAT5A/qoekq0kYTS7Ymgqj7pq3xIPfHUUCgYEA568H8/qyhmrna84pAQf9gz3ln6EQWm/RfdOi+v42ZdL6sjmpHfT0VYaBuxc54D6OvhvPSoYizhZaHLuDnioaGwkDgducA057EIumDgn2Fvw1mUfcKymGngk4Z5GiWsFqJ66yO5X7ci/4JaD9rG8sKI0JKkhfhL0EyrzgWIykg4kCgYEAvy0eus9EDsEdSL2bNT0/Cd5wi/cEUVbhyLGhSXkjIxlIAHR7aU1L0qhaVE2VJ2Tp91tksGiw+gLvRoFne7sFnCqN/aNm1YhkkVW9QPYRv//B0tD595aOYhjRFwlM3ncekJcNmixnSHf78w3/+dZFgV8xKkOxiS8pVcREeBGxW20CgYBAbLuZbK0YE8ImiD1+u+oTBLNFoFQb0dw/UQqRIP+fcPulc8NDQUpwPeb1T5AYe0zWMIWEA6jKBg0o0DvZT3vS6L7A7YCEqt4ty6dxX/O+kIOXDBR9LB7y8z1sD2NGOWJ7hmipiRtStWQbkpj3yjJNVGqoB1gIYUdj2QHJndJhgQKBgQDTkCUFF0CgiBWUIyI96RkaSW/9/+3PAFojgHrbp93RLsW18j+YVZOyvQshhmNjlhEs2cONLYdNl5kPEi4yt/f8TrFbKBSgBlO0t9u0z0tAo+xfpocTzmYCw1eDnkXWxzZLwBSsB3Vkt7GJb11Uee7HW4MjHOTXuUvdQ8Alg+NXqw=="
    brPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3QDuQlynuboCyAinT3gFxO/+FePOAT2HWVTKHsQqFje78BVdXVvAMo7DmL7zDmEnfzDgqhNLCuAjf03/Oe52pTKgOaFPjCBFJG2/islxV6TRYvyy4vBRhh0IE0BQEvk4pM9bB7WIN1vBu8ECbEwylxkO3RB/aSb90Wxmc0J05c4/9W6yfLgxl2JilT69jG7jprcws83fTtHDztXxFcKZyWwFH0MWZXjFC9tTqZJk46iAUHwDX/9uA42yXpWY0VAO2CEeNl6cRl1njpV0dQ948yDdJYLmnMMvnp9yb4WwuthOn9OK86rN004ZSsR+HIxWYzj76BppdmeN0tZOOpT47QIDAQAB"
    appId: "bairong"
    isProxy: true
spring:
  rabbitmq:
    addresses: delivery-rabbitmq-cluster-01.brapp.com:5672
    username: strategy_distribute
    password: strategy_distribute
    publisher-confirms: true
    publisher-returns: true
    virtual-host: marketing-flow
innerSftp:
  uploadpath: /UploadFiles/marketing/
#elastic-job配置
SERVER_LISTS: speed-zk-01.brapp.com:2181,speed-zk-02.brapp.com:2181,speed-zk-03.brapp.com:2181
NAMESPACE: marketing-job
BASE_SLEEP_TIME_MILLISECONDS: 1000
MAX_SLEEP_TIME_MILLISECONDS: 3000
MAX_RETRIES: 3
NESTED_PORT: -1
NESTED_DATA_DIR: target/test_zk_data/

