# Ice Default locator
Ice1.Default.Locator=\
  BrIceGrid/Locator:\
  tcp -h ice1-master.brapp.com -p 4061:\
  tcp -h ice1-replica.brapp.com -p 4061
Ice2.Default.Locator=\
  DacIceGrid/Locator:\
  tcp -h ice2-master.brapp.com -p 4061:\
  tcp -h ice2-replica.brapp.com -p 4061

# Ice1 prop
# 线程池初始大小
Ice1.ThreadPool.Client.Size=20
# 线程池最大数
Ice1.ThreadPool.Client.SizeMax=100
# ICE服务客户端线程栈大小设置
Ice1.ThreadPool.Client.StackSize=4096
# 建立连接超时时间
Ice1.Override.ConnectTimeout=2000
# 服务调用超时时间
Ice1.Default.InvocationTimeout=20000
# If this property is not defined, the default behavior is to retry once immediately after the first failure
Ice1.RetryIntervals=0 1000 5000
# 心跳
Ice1.ACM.Heartbeat=2
# 不关闭连接
Ice1.ACM.Close=0
# 最大消息大小, 默认值1024KB
Ice1.MessageSizeMax=65536

# Ice2 prop
# Ice2.ACM.Timeout=0
Ice2.ThreadPool.Client.Size=20
Ice2.ThreadPool.Client.SizeMax=100
Ice2.ThreadPool.Client.StackSize=4096
Ice2.Override.ConnectTimeout=2000
Ice2.Default.InvocationTimeout=20000
Ice2.RetryIntervals=0 1000 5000
Ice2.ACM.Heartbeat=2
Ice2.ACM.Close=0
Ice2.MessageSizeMax=65536

# Ice 自定义配置
# 通信器空闲时间
Ice1.IdleTimeOutSeconds=86400
Ice2.IdleTimeOutSeconds=86400