sharding:
  jdbc:
    datasource:
      names: ds0
      ds0:
         url: jdbc:mysql://192.168.162.192:3306/test_loan?useUnicode=true&characterEncoding=UTF-8
         username: rule_service
         password: rule_service_2015-09-10
         type: com.alibaba.druid.pool.DruidDataSource
         driver-class-name: com.mysql.jdbc.Driver
         filters: stat
         maxActive: 300
         initialSize: 1
         maxWait: 60000
         minIdle: 1
         timeBetweenEvictionRunsMillis: 60000
         minEvictableIdleTimeMillis: 300000
         validationQuery: select 'x'
         testWhileIdle: true
         testOnBorrow: false
         testOnReturn: false
         poolPreparedStatements: true
         maxOpenPreparedStatements: 20
  config:
        sharding:
          props:
            sql.show: true
logging:
    level:
        com.br.off.mapper: debug
    file: ./logs/core.log
    root: INFO
otherConfig:
  alarm:
        secretKey: 412a281869db3e152d5a276ad444fade
        mails: xinke.liu@100credit.com,guang.chen@100credit.com,runtong.yuan@100credit.com
        sendCode: 66618706
  userCenter:
        appName: loan-strategy
        appSecretKey: 404be42e9ad8ce59af79f17eb51594cf
  warning:
        pageSize: 5000
        apiUrl: http://compass-api.100credit.com/api/loan-warning-api/loanStrategy/v2/query
        path: /Users/chao.z/Desktop/
        ftpHost: 10.100.123.65
        ftpPort: 21
        ftpUsername: dev-controller
        ftpPwd: 9PdaRcMRphcNctRy
        email:
          notice: nengwu.qu@100credit.com,chunliu.le@100credit.com,qianqian.cao@100credit.com,xinke.liu@100credit.com
  encodeMapping:
        appName: loan-warning
        appSecretKey: f15a1421ac95a284683688af14688b72
cluster:
  flag: k8s-prod-a
api:
  dass:
    baseUrl: http://testdaas.huiyunai.com
    postHermesUserData: ${api.dass.baseUrl}/csos-daas/call/postHermesUserData
    aeskey: ovksl39fcl13m9dF
    SecretKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJ4W9Hw1Kb6g0RevKSeKqriBCup3x8V2G2J63imkypbtPV+RJjq4eCqcd7s2FI/9eTSMw17675Ey9MkKndIckvpxT1iCtUnuRbg1ICtZ127t65GhOPchBzWHoC+rG56Rw4NhpsvpIGC1y4EUx26TyNop7HRekKwosAnnl6QDWBEdAgMBAAECgYAkX7W7CmRjdw8E+wlmDrK/JvnC/vJZDZa5bvnE7SSr20Qew//ezOjhLQUjbwsGIlUL8UNWjDgo2WeXBjlPycFLP8YN/+gUPR/bfftUY4cTnWzAAKKyUJBeyt3SqaeYcUhW3aUCUlaVAb8ZdyIu4WlHYHhlkSoXrDRvnqlJmyj8wQJBAMzApuvsJDZIX6qvMGR6YTvqPIsl47+qIlk7iTUfwbjGz5zlFtu4IRd+ZVdHlncg5arrl+lOw33rkHhxtnV8jO0CQQDFqGsIPk4Nnwsx9XtCCrYePvgydzEAT1nr4gBUkXbvavMyJKsQWI5AXUAInNuqxRvNfjh3GMaWstIsMQJyDj7xAkEAglL1bCEIA40ZZ1jO4oWKskorcx4Q0oQGDOn6MVgfQ+83YlPmsr+GQJ/w/RbRzM2hoaMHNDcv80wmzqMCUdGPGQJAKIHuhX73UhVRHwj3HL7DOgmfpgAFW9HnVM85UBuLq19YveMD59KuPISf1eQHpMTGgOOoQMgkEshNCF9259cBkQJBAKIlpXnTHvv2M96B7w7T1RYVvjke4LLpCbAVd8fBciOdFLmMh0+FThxGWijgfow1XYaPrU0DlfLpkfLrgk3LWUQ=
  twoSeven:
    baseUrl: http://8.129.19.178:8888
    zhuangku: ${api.twoSeven.baseUrl}/zhuangku
    isProxy: 1
  marketing:
    baseUrl: http://k8s.brapp.com/compass-api/api/marketing-api
    transferUrl: ${api.marketing.baseUrl}/marketingTransferData/receiveTransferDataSync
    uploadUrl: ${api.marketing.baseUrl}/marketingUserPre/receiveMarketingPreUser
  halo:
    openUrl: https://fat-hello-openapi.hellobike.com/openapi
    appKey: hellobikefinance-bwYuIVvO
    secret: b3392af427b6449e94269433bdf5fb58
    method: hello.finance.loan.marketing.callback
    isProxy: false
  xiecheng:
    openUrl: https://cgcallback-fat.ctripqa.com/nemoweb/ad/common/outAdMonitor.do
    appId: bairong001
    appIdVt: test002
    keyVt: 6b219b9e71fdb2d2
    ivVt: 5e7b6c07d3edbc01
    signKeyVt: b8845b4cb1f16471
    key: f3df6f62f0527bf0
    iv: 3b2dac323465b024
    singKey: 95cc01ec07387a44
    source: BaiRong_C01
    channel: commonOutAdMonitor
    isProxy: false
  zhongAn:
    baseUrl: https://finance-gateway-test.diandian.com.cn
    api: ${api.zhongAn.baseUrl}/fcpGateway
    isProxy: false
    rsapKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCVuaxc7ZznPdvsH0nhd2eQ/uhu/LewJqUVMvdYUKwXPxzGBUz8cVKyltwpMJ03uMPx+RStWnkWcmCSeQdqiw27FtaPELOxxQQc06OGBXfp5R86MKp2+bkdPRSkpUKK2X8vCyiopQojBXbaVzRUwjPPsQAsDinCGkSUirWETxfCxwIDAQAB
    xdCode: 07brdyy01
    bxCode: 3360001
  didi:
    baseUrl: https://admarketing-manhattan.xiaojukeji.com
    smsUrl: ${api.didi.baseUrl}/crow/collision/bairong
    reachUrl: ${api.didi.baseUrl}/crow/user/success/bairong
    jmassSUrl: ${api.didi.baseUrl}/model/sample/bairong
    failedUrl: ${api.didi.baseUrl}/crow/faileduser/mediaName
    token: DK&SgWl!fZ%WVSXe
    scas : "0001"
    channelId: 3140738898634899
    isProxy: false
innerSftp:
  uploadpath: /UploadFiles/marketing/
#elastic-job配置
#elastic-job配置
SERVER_LISTS: speed-zk-01.brapp.com:2181,speed-zk-02.brapp.com:2181,speed-zk-03.brapp.com:2181
NAMESPACE: warning-job
BASE_SLEEP_TIME_MILLISECONDS: 1000
MAX_SLEEP_TIME_MILLISECONDS: 3000
MAX_RETRIES: 3
NESTED_PORT: -1
NESTED_DATA_DIR: target/test_zk_data/
corn:
  closeDateAlarmJob: 00 00 10 * * ?
  sftpDeleteMonitorJob: 00 0/2 00-23 * * ?
  ftpDeleteMonitorJob: 00 0/2 00-23 * * ?
  finishPutJob: 00 00 10 * * ?
  ftpToDbJob: 00 0/2 00-23 * * ?
  sftpToDbJob: 00 0/2 00-23 * * ?
  monitoringExpirationAlarmJob: 00 00 10 * * ?
  progressReportJob: 00 00 09 * * ?
  reportJob: 00 00 18 * * ?