#沙子
scorencashonszyxxy=flag_score,scorencashonszyxxy
scoremcashonxhqbdzcd=flag_score,scoremcashonxhqbdzcd

#民生卡中心
scoremcashon360xktwo=flag_score,scoremcashon360xktwo
scorebrevoloanmszd3=flag_score,scorebrevoloanmszd3

#es prod需要申请账号
es.hosts=192.168.121.211:9200,192.168.121.212:9200,192.168.121.213:9200
es.username=pd_str_marketing
es.password=pd_str_marketing-20210621
es.connectTimeout=20000
es.readTimeout=100000
es.connectionRequestTimeout=300000
es.threadCount=8
