##Ĭ��ֵfalse
#speed.enable.remote.conf=true
##��ȡԶ��������Ϣ�ķ�����������
##speed.conf_server_host=speed-api.100credit.cn
#speed.conf_server_host=speed-api-pre.brapp.com
##Ӧ������������д�������쳣
#speed.app=compass_app
##��������������д�������쳣
#speed.topic=compass_topic
##��ȡ�����ļ���Կ��������д�������쳣
##dev
##speed.secretkey=719be7872fec85171e2bdd7332288b93
##pre
#speed.secretkey=19414d88e0bfdd4820a0c31c9fe9093f
##prod
##speed.secretkey=552104ad8cbcd5d2ab188c8b908902b5
##����:test,pre,sim,prod
#speed.env=pre
##�����йܵ�������
#speed.ignore
##��ȡԶ�����õ����Դ���(��������ô��ڵ���3,��ֹ���粻�ȶ������ػ�ȡʧ��,)
#speed.conf_server_url_retry_times=3
##����ʱ����
#speed.conf_server_url_retry_sleep_seconds=1
##Զ�������ļ��ı������ش洢·��
#speed.user_define_download_dir=/opt/data/inloan
##�Ƿ������ļ���������classpath·����
#speed.enable_local_download_dir_in_class_path=false