sharding:
  jdbc:
    datasource:
      names: ds0
      ds0:
        url: jdbc:mysql://192.168.162.192:3306/test_loan?useUnicode=true&characterEncoding=UTF-8
        username: rule_service
        password: rule_service_2015-09-10
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 300
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  config:
    sharding:
      props:
        sql.show: true
logging:
  level:
    com.br.marketing.mapper: debug
eureka:
  client:
    service-url.defaultZone: http://192.168.162.193:1111/eureka/
##    service-url.defaultZone: http://192.168.23.121:18000/eureka/


spring:
  rabbitmq:
    zw:
      addresses: 192.168.23.73:5672
      username: strategy_distribute
      password: strategy_distribute
      publisher-confirms: true
      publisher-returns: true
      virtual-host: marketing-flow
    yz:
      addresses: 192.168.23.73:5672
      username: strategy_distribute
      password: strategy_distribute
      publisher-confirms: true
      publisher-returns: true
      virtual-host: marketing-flow
    listener:
      retry:
        enabled: true
        max-attempts: 5
        initial-interval: 3000
      acknowledge-mode: manual
      default-requeue-rejected: false
      auto-startup: true
  web:
    interceptors.enabled: true
  sql.source: prod
cluster:
  flag: k8s-prod-a
otherConfig:
  alarm:
    secretKey: a9c57e4138807a9e18b439cd9dab275b
    appName: marketing
  encodeMapping:
    appName: loan-warning
    appSecretKey: f15a1421ac95a284683688af14688b72
  userCenter:
    appName: loan-strategy
    appSecretKey: 404be42e9ad8ce59af79f17eb51594cf
api:
  intelligentCustomerService:
    baseUrl: https://helios-pre.100credit.com/zuul/api/helios-app-api
    pushUserUrl: ${api.intelligentCustomerService.baseUrl}/third/process/data
  robotAiApiService:
    baseUrl: http://k8s.brapp.com/compass-api/api/robotai-api-service
    robotOutboundUrl: ${api.robotAiApiService.baseUrl}/api/robotOutbound  #转化推送智能客服
  customerService:
    apiCode: 4000296
