eureka:
  client:
    service-url.defaultZone: http://192.168.21.20:18000/eureka/,http://192.168.21.29:18000/eureka/

otherConfig:
    huaXiangInterface:
          getAllProductTypes: http://192.168.22.212:8080/SendBox/ProductTypes
          getAllProducts: http://192.168.22.212:8080/SendBox/Products
          getPorductByType: http://192.168.22.212:8080/SendBox/Products/
          getReport: http://192.168.21.200:8080/huaxiang/v1/get_report
    sanxiangzhiliInterface:
          sanxiang_url: http://zh-service/v1/getData
          haina_url: http://HAINA-SERVICE/query
    alarm:
          secretKey: 7edd43e33ddb8f3d6b38cb68c6c79a33
          mails: xinke.liu@100credit.com,guang.chen@100credit.com,runtong.yuan@100credit.com
          sendCode: 55518704
    mq:
          destinationName: strategy_online_query_log
          appName: strategy_online_query_producer
          appSecretKey: 9f1b8afa556a01d4d47ecfec9818da93
    userCenter:
          appName: loan-strategy
          appSecretKey: 7357430aa11febfe81d45945c02706b3
  encodeMapping:
        appName: loan-warning
        appSecretKey: a938d0e974746651a11ddcdbcea31404
