#推送客服的apicode
apiCodeOfpushCustomer=["3710012","4004643","3710004","3710030","7410437","7410780","7410794","7410797","7410785","7412002","3710034","7410787"]
#推送哈啰的apicode
apiCodeOfpushHaluoByTransfer=["3710028","7410850"]
#是否是标准客服转化接口
customerTransferIsYx={"3710012":true,"7410787":true}
#海尔apicode
haierApiCode=["3710018","7410930"]
#玖富apicode
jfApiCode=["7412002","3710034"]
#记录taskid时间的apicode
apiCodeOfRecordTaskTime=["3710028","7410437","7410850"]
#去重线程数
soleNum=20
#萨摩耶场景转化需要判断的场景
groupTypeSaMoye=["S01","S02","S0202","S04","S06","S08"]
#数禾apicode
shuheApiCode=["3710004","7410785"]
#走通用流程apiCode
universalProcessApiCode=["7412003","3710012","7410930","3710018"]
#客户使用规则映射
customerRuleMapping={"7412003":"YiXin","3710012":"YiXin","7410930":"Haier","3710018":"Haier"}
# 数禾转化数据提取分场景, T 代表当前天到月底； T+/-day 代表当前天到day天;
## eg：{"促首登":"T","促申完":"T-15","促首借":"T+31","促复借":"T+0"}
shuHeTransferExtractDayMap={"促首登":"T","促申完":"T+15","促首借":"T+31"}
# 数禾转化数据提取apiCode集合
shuHeTransferExtractApiCodes=["3710004","3710023","7410785"]
# 数禾转化数据提取任务开始时间
shuHeTransferExtractJobStartTime=07:00:00
# 数禾有效期, T 代表当前天到月底； T+/-day 代表当前天到day天;
## eg：{"促首登":"T","促申完":"T-15","促首借":"T+31","促复借":"T+0"}
shuHePeriodOfValidityDayMap={"促首登":"T","促申完":"T+15","促首借":"T+31"}
#宜信非实时typelist
yixinNoRealTimeType=["13","12","9","7","17","18","6","11","14","8","4","15"]
#电销文件定制处理集合
dxFileCustomize={"yixin":["3710012"],"xw":["4004666"],"juzi":["3710037"]}