datasource:
  marketingWrite:
    name: marketing
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.100.151.104:4000/marketing?useUnicode=true&characterEncoding=UTF-8
    username: u_pd_marketing
    password: f9daIYUIAXQkeyVbDoOI
  druid:
    initialSize: 5
    maxActive: 300